version: '3.7'

services:
  licensing-service:
    build: .
    image: andmarsh/licensing-service
    container_name: "licensing-service"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "licensing-service"
networks:
  backend:
    driver: bridge
