spring:
  application:
    name: config-server
  profiles:
    # Uses latest as default
    active: native
  cloud:
    config:
      server:
        # Local configuration: This locations can either of classpath or locations in the filesystem.
        native:
          # Reads from a src/main/resources/config
          search-locations: classpath:/config
        git:
          # Just as an example, this points to the same config files as native but on GitHUB, use different repo for real projects
          uri: https://github.com/and-marsh/spring-microservices-in-action.git
          search-paths: config-server/src/main/resources/config
        vault:
          port: 8200
          host: vault-server
          scheme: http
          authentication: token
          token: '{cipher}6abb90fa7272541341e007dbd2970ca4c91bae1688dc4d161e237ec6291dde27434900cb42e9f98602e615e05bf35b85'
          kvVersion: 2
server:
  port: 8071
encrypt:
  # Don't use this in production! This should be supplied as ENCRYPT_KEY env variable
  key: z0=bwYgboe_Rp*[
