eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: eureka-server
  server:
    waitTimeInMsWhenSyncEmpty: 5
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
server:
  port: 8070

cloud.loadbalancer.ribbon.enabled: false
