example:
  property: I AM DEV
management:
  endpoint:
    env:
      show-values: ALWAYS
    health:
      show-details: ALWAYS
spring:
  datasource:
    password: '{cipher}09f63af6410f6f5b5d257a33e5325a54c740576750011165df68e7eaba668116'
    url: jdbc:postgresql://database:5432/ostock_dev
    username: postgres

logging:
  level:
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
